### ISSUE TITLE
PingStart: nonretriable error response: 404 Not Found

### ISSUE THREAD

**Issue by lakemike** [bdd/runitor#11]
I have tried to use runitor with a self-hosted healthchecks instance, but failed so far.

Curl approach works fine:
> m="test"; myserver="serveraddress"; code="apicode"
> curl -fsS --retry 3 --data-raw "$m" https://$myserver/ping/$code > /dev/null

runitor command throws an error:
> myserver="serveraddress"; code="apicode"
> runitor -api-url="https://$myserver" -uuid=$code -- echo "test"
> 2021/01/31 11:44:11 PingStart: nonretriable error response: 404 Not Found
> test
> 2021/01/31 11:44:11 PingSuccess: nonretriable error response: 404 Not Found

Is this a known issue? Anything I can do?

Thanks!

**Comment by bdd** [comment]
Looks like your instance runs on  `/ping` request path, unlike the service instance on hc-ping.com which is available at the root.

So you should pass `-api-url="https://$myserver/ping"` as the argument.

**Comment by lakemike** [comment]
Excellent! That worked. But now I encountered the next problem: When i try to put a command after "--" I had assumed it would take everything following the "--". But this does not seem to be the case because a pipe "|" character is not taken into the execution by runitor.

**Comment by bdd** [comment]
## Short Answer
Piping via `|` is the feature of shell. Runitor will get executed only with the parameters up to the `|`.

If you want runitor to execute a shell for you, then you can replace the command with your shell of your choice and pass the shell command to be evaluated:

_e.g._:
```
% runitor -api-url=https://example.com/api -- bash -c "my_cmd --flag=y foo | grep -v error:"
```

## Long Answer 

When you invoke `runitor -api-url=https://example.com/api -- my_cmd --flag=y foo | grep -v error:`, shell will execute runitor with args: 

It will first create an anonymous pipe with two ends.

Then execute runitor, and set its argument array to:
0. runitor
1. -api-url=https://example.com/api
2. --
3. my_cmd
4. --flag=y
5. foo

...and then replace the stdout file descriptor of this process with one end of the pipe. Execute `grep` with arg array `["grep", "-v", "error:"]` and connect its stdin descriptor to the other end of the pipe created above, connecting standard output (mind you, not standard error) of the left hand side invocation to the standard input of right hand side invocation.

You can see a nice illustration of how shell parses its command on explainshell.com
https://explainshell.com/explain?cmd=runitor+-api-url%3Dhttps%3A%2F%2Fexample.com%2Fapi+--+my_cmd+--flag%3Dy+foo+%7C+grep+-v+error%3A#
