### ISSUE TITLE
docker pull fails with docker rootless

### ISSUE THREAD

**Issue by r3mi** [bdd/runitor#174]
Hello,
thanks for this useful project !

I switched from docker "default" (root) to [docker rootless](https://docs.docker.com/engine/security/rootless/) , and unfortunately I can no longer pull runitor images.

```
$ docker pull runitor/runitor:v1.2.0-ubuntu
v1.2.0-ubuntu: Pulling from runitor/runitor
bccd10f490ab: Already exists 
059bea526c98: Extracting [==================================================>]  2.215MB/2.215MB
bea230f2086c: Download complete 
failed to register layer: lsetxattr user.overlay.impure /usr: operation not supported
```

using this version:
```
$ docker info
Client: Docker Engine - Community
 Version:    26.1.0
 Context:    rootless
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.26.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
(truncated)
```

Same problem with docker 26.0.2

Same problem when pulling from GHCR: `docker pull ghcr.io/bdd/runitor:v1.2.0-ubuntu`

It works OK with docker in docker default (root) mode, with the same versions of docker.

I searched for an answer: might be related to these issues ?
https://github.com/jsknnr/enshrouded-server/issues/56
https://github.com/containers/storage/pull/1847
i.e. images built with a problematic version of `buildah`  ?

**Comment by bdd** [comment]
Images are [build with Podman](https://github.com/bdd/runitor/blob/main/scripts/mkoci#L55), which [uses Buildah](https://podman.io/blogs/2018/10/31/podman-buildah-relationship.html).

Looks like Nixpkgs unstable when I last built the images (2 weeks ago) had` Buildah 1.33.5, tagged Feb 1st.
```
% nix run pkgs#skopeo -- inspect docker://docker.io/runitor/runitor:v1.2.0-ubuntu \
  | jq -r '.Labels["io.buildah.version"]'
1.33.5
```

I now have 1.35.3, [tagged March 29th](https://github.com/containers/buildah/commit/9f0251c1111dc189673c48062d43335f912b81a7).
```
% nix run pkgs#buildah -- --version
buildah version 1.35.3 (image-spec 1.1.0, runtime-spec 1.1.0)
```

Let's rebuild all the images and push again.

```
% nix run pkgs#skopeo -- inspect docker://docker.io/runitor/runitor:v1.2.0-ubuntu \
  | jq -r '.Labels["io.buildah.version"]'
1.35.3
```

Alright. Can you try again to see if this version of Buildah fixes the issue reported in https://github.com/containers/storage/pull/1847

**Comment by r3mi** [comment]
yes, it works ok now.
docker pull is ok.

Thank you, it was very quick !

**Comment by bdd** [comment]
Well, thank _you_ for filing an issue with good investigation with correct diagnosis of the problem. I just typed a few commands :)
