### ISSUE TITLE
About the release scheme

### ISSUE THREAD

**Issue by chenrui333** [bdd/runitor#178]
👋 while reviewing [this homebrew pr for runitor](https://github.com/Homebrew/homebrew-core/pull/202748), I am seeing some suffix `-build.x` for the release tag, any reason of not using a more semantic versioning scheme like `x.x.x.<build-number>`? Thanks!

**Comment by bdd** [comment]
runitor uses [Go's module versioning scheme](https://go.dev/doc/modules/version-numbers).

Your example of `major.minor.patch.build-number` also would neither be SemVer 1.0 nor 2.0. It's possible to be SemVer 2.0 compliant by changing the dash before build to a plus, e.g. `v1.3.0-build.4` becomes `v1.3.0+build.4`. _(see https://regex101.com/r/Ly7O1x/3/ online, linked from semver.org)_.  I don't intend to make such a change currently.

Side bar: `-build.X` tags are used solely for binary distribution only GitHub releases. They are rebuilds of the same vX.Y.Z, with a newer version of Go, to bring in bug / vulnerability fixes, resource footprint improvements, etc. Packagers should ignore these build tags, and use vX.Y.Z ones. Like we do in Nixpkgs https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/ru/runitor/package.nix.

**Comment by chenrui333** [comment]
oh, yeah, I was thinking about `+build123`. make sense, I can just do the `x.x.x` part for the brew releases, thanks!
