### ISSUE TITLE
HC_API_URL env variable doesn't work as expected

### ISSUE THREAD

**Issue by rwjack** [bdd/runitor#26]
Method 1 - Works:
```
runitor -api-url="https://example.com/ping" -uuid 123-abc-456-def -- echo test
```
Method 2 - Works:
```
HC_API_URL="https://example.com/ping" runitor -uuid 123-abc-456-def -- echo test
```
Method 3 - Doesn't work:
```
HC_API_URL="https://example.com/ping"
runitor -uuid 123-abc-456-def -- echo test
runitor -uuid 789-ghi-012-jkl -- echo test2
```
Tested all sorts of combinations, can't get cron to execute method 3, which is the cleanest one for having multiple jobs, but only if I could set the HC_API_URL variable.

**Comment by bdd** [comment]
Method 3 would only work if it was a shell script, executed by the cronjob.
If you're adding these as separate cron job entities, they execute separately, without state.

If these jobs needs to execute in different schedules, but not serially, then you have to prefix your cron entries either with the environment variable like in Method 2 or pass the `-api-url` parameter in each.
