### ISSUE TITLE
Feature Request: Custom Header Support

### ISSUE THREAD

**Issue by milindpatel63** [bdd/runitor#30]
I am self-hosting my healthchecks instance and I have exposed it publically via Cloudflare tunnel.
I want to secure it using Cloudflare Access. And verify requests using Cloudflare service token headers...
It would be great if runitor supported setting custom headers.
I can do it manually via curl.
If you have got time, would love to have this feature.

**Comment by bdd** [comment]
This would be a good first issue for a first time contributor to the project.
Let's see if someone wants to pick it up.

**Comment by bdd** [comment]
Well, no pickers in until now.
Committed a quick implementation and cut a beta release.

@milindpatel63: Give [v0.10.0-beta.1](https://github.com/bdd/runitor/releases/tag/v0.10.0-beta.1.) a try.
Release message has an example, addressing your use case.

**Comment by bdd** [comment]
One last beta before release https://github.com/bdd/runitor/tree/v0.10.0-beta.3

**Comment by bdd** [comment]
This was shipped in v0.10.0.
