### ISSUE TITLE
error: the input device is not a TTY

### ISSUE THREAD

**Issue by brunoamaral** [bdd/runitor#34]
```
the input device is not a TTY

[runitor] Command exited with code 1.
```
Maybe this is me running the command wrong. It's a crontab that runs a docker exec.

`/usr/local/bin/runitor-v0.8.0-linux-amd64 -uuid UUID -- /usr/bin/docker exec -it admin ./manage.py runcrons`

**Comment by brunoamaral** [comment]
removing the `-i` option from `docker exec` solves this problem.

**Comment by bdd** [comment]
For completeness and future reference in case someone finds this issue:

The `-i / --interactive` parameter to Docker instructs the client to keep stdin open even if it's not attached. Coupled with `-t / --tty` it expects to read from at pseudo terminal. In your invocation, there's no interactivity and also there's no terminal as it's run by cron.  `The input device is not a TTY` error was coming from Docker.

I recommend removing `-t` as well. You don't need it.
