### ISSUE TITLE
Ping body limit?

### ISSUE THREAD

**Issue by joshlopes** [bdd/runitor#62]
Not sure if it's a runittor issue or something else but I am using Runitor v0.10.1 (latest) witn the following configuration

```
/home/user/go/bin/runitor -uuid xx -api-url $APIURL -ping-body-limit=0 -- /bin/bash -c "cmd"
```

This used to work fine but now the logs are being truncated. 

![image](https://user-images.githubusercontent.com/3440849/193619717-36eb639a-f4d4-4c30-8455-2c4134de26f1.png)

Not sure why?

**Comment by bdd** [comment]
I believe truncation is done on the server side. Check your instance's [ping body size limit configuration](https://healthchecks.io/docs/self_hosted_configuration/#PING_BODY_LIMIT).
A telltale sign of server side truncation is the abrupt ending of logs. Runitor implements ping body limiting with a tail buffer, so you always get the last N-bytes of the output. Healthchecks server implements a head buffer. That's what's happening in the example truncated log above.
