### ISSUE TITLE
Regression: API URL handling changed with release 1.1.0

### ISSUE THREAD

**Issue by GermanCoding** [bdd/runitor#75]
Before commit https://github.com/bdd/runitor/commit/bac48145c9261c01444adc01f74bf27dc8cd6b28, runitor would always append a `/` to the given API URL (`-api-url` or `HC_API_URL`). Since the stated commit this is no longer the case and given URL's are treated as-is, without appending a /. This can result in a breaking change, creating 404 errors due to invalid ping URLs being generated.

Examples:

### runitor 1.0.0 behaviour:

`HC_API_URL="https://healthchecks.example.com/ping/"`
`runitor --uuid foobar`

generated final request URL:

`https://healthchecks.example.com/ping//foobar` (double slash is not removed, but usually automatically fixed/ignored by webservers)

`HC_API_URL="https://healthchecks.example.com/ping"` (no final slash)
`runitor --uuid foobar`

generated final request URL:

`https://healthchecks.example.com/ping/foobar` (one / automatically appended)

### runitor 1.1.0 behaviour:

`HC_API_URL="https://healthchecks.example.com/ping/"`
`runitor --uuid foobar`

generates final request URL:

`https://healthchecks.example.com/ping/foobar?rid=runid` (single slash)

`HC_API_URL="https://healthchecks.example.com/ping"` (no final slash)
`runitor --uuid foobar`

generates final request URL:

`https://healthchecks.example.com/pingfoobar?rid=runid` (**zero slashes used. Likely results in invalid URLs, generates 404 errors**)

**Comment by Derkades** [comment]
Thank you for opening this issue, this explains why my checks are failing after updating to 1.1.0

**Comment by bdd** [comment]
This is a regression I should have caught. Sorry for the dumb breakage.

As soon as I reach to the hotel, I'll cut a patch release, fixing use of new url.JoinPath function.

P.S. Bummer, nobody ended up testing the beta release and reporting back either. GH follows should normaly notify new pre-releases but then again not many people follow it. I should consider creating an announce mailing list.

**Comment by GermanCoding** [comment]
All good, thanks for caring!

I do have GitHub release notifications on actually, but I often tend to ignore prereleases. I always feel like I won't have the time to manually test them properly, so I naturally tend to just rely on stable releases. Of course when everyone does that the prerelease becomes useless - a typical issue with these types of projects.

For the future I'm going to try and setup a beta/RC channel for runitor. I have recently setup a Debian package for runitor (https://github.com/GermanCoding/runitor) sourced from official releases (it actually just repackages the official binary so signatures are preserved - it's not build from source). Then I will look into running a few runitor beta's here and there.

**Comment by GermanCoding** [comment]
Yes, I can also confirm that this fix works. In addition, the double slash is now also a single slash in both cases:

### runitor 1.1.1-rc.1 behaviour:

`HC_API_URL="https://healthchecks.example.com/ping/"`
`runitor --uuid foobar`

generates final request URL:

`https://healthchecks.example.com/ping/foobar?rid=runid` (single slash)

`HC_API_URL="https://healthchecks.example.com/ping"` (no final slash)
`runitor --uuid foobar`

generates final request URL:

`https://healthchecks.example.com/ping/foobar?rid=runid` (also single slash)

In fact, any number of trailing slashes are coalesced into a single slash:

`HC_API_URL="https://healthchecks.example.com/ping//"`
`runitor --uuid foobar`
`https://healthchecks.example.com/ping/foobar?rid=runid`

Do you want this closed now or on final release?

**Comment by bdd** [comment]
Thanks for confirming.

> Do you want this closed now or on final release?

I'll close it when 1.1.1 is out.

**Comment by bdd** [comment]
v1.1.1 is out.
Go module v1.1.0 retracted.

https://github.com/bdd/runitor/releases/tag/v1.1.1
