### ISSUE TITLE
307/308 redirects aren't handled well

### ISSUE THREAD

**Issue by apeschar** [bdd/runitor#79]
I want to use a custom domain for pings, and delegate to the healthchecks.io service, so that if I decide to self-host in future, I can do that without changing the API URL everywhere I use runitor.

This works fine by setting HC_API_URL to the redirect server, which just redirects to the same path on hc-ping.com.

A 301/302 redirect works, except that the body is not sent on the second (redirected) request to hc-ping.com. For this use case I discovered [307/308 redirects](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307) which require re-sending the request body.

Go supports this, but [requires that GetBody be implemented](https://devdocs.io/go/net/http/index#NewRequestWithContext), if not using *bytes.Buffer, *bytes.Reader, or *strings.Reader.

Implementing GetBody with the RingBuffer involves adding seeking functionality to the RingBuffer. Currently the RingBuffer allows for just one read. I stopped here because it seems involved.

I'd like to ask for your opinion, as I see two approaches:

1. Add seeking functionality to the RingBuffer so that the request body can be read again, and GetBody can be implemented.
2. Convert the RingBuffer to a *bytes.Buffer once, and rely on Go's automatic handling.

The second approach seems simpler and would also allow us to get rid of some extra code, as this would happen automatically: https://github.com/bdd/runitor/blob/main/internal/api.go#L147-L164

The only real downside would be a little extra memory use for one extra copy of the request body. But this seems very insignificant.

Do you have any thoughts?

**Comment by bdd** [comment]
I don't have a strong preference for either approach.

Implement whichever you feel like and I'll gladly accept the PR. Just make sure it comes with ample unit/regression tests.

**Comment by apeschar** [comment]
Fixed in c2cea80.

**Comment by bdd** [comment]
Let's keep this open until a release including the fixes discussed here gets released.

**Comment by bdd** [comment]
v1.2.0-beta.1 is out https://github.com/bdd/runitor/releases/tag/v1.2.0-beta.1

Can you please test this beta release?

A 307/308 redirecting HTTP service for testing can be found in [this gist](https://gist.github.com/bdd/285f107bdac187e2a50730b563b1c870).

```
% go run 307.go -addr ":8880" -code 307 &
% runitor -api-url http://localhost:8880 -uuid <testing_uuid> -- sh -c "echo whee. on a trampoline." 
```

/cc @GermanCoding

**Comment by apeschar** [comment]
Works for me. :)

If everything works correctly the date should be visible in the request body in the healthchecks.io UI.

Testing this version via Nix:

~~~sh
nix-shell \
    -p 'runitor.override ({ buildGoModule, ... }: {
        buildGoModule = attrs: buildGoModule (attrs // rec {
            version = "1.2.0-beta.1";
            src = fetchFromGitHub {
                owner = "bdd";
                repo = "runitor";
                rev = "v${version}";
                hash = "sha256-lL9yfiqPIIfEvjiWcG6e1NrURHJFdk4x/od/w7/i2DE=";
            };
            ldflags = attrs.ldflags ++ ["-X main.Version=v${version}"];
        });
    })' \
    --run 'HC_API_URL=<testing-server> runitor -uuid <testing-uuid> date'
~~~

Apache config to use 307 redirect for clients that support it, and 302 redirect for older clients:

~~~apache
RewriteEngine On

RewriteCond %{HTTP_USER_AGENT} ^runitor/v(1\.([2-9]\d*|1\d+)|[2-9]|1\d+)
RewriteRule ^(.*) https://hc-ping.com$1 [R=307,L]

RewriteRule ^(.*) https://hc-ping.com$1 [R=302]
~~~

**Comment by bdd** [comment]
> ```shell
> nix-shell \
>     -p 'runitor.override ({ buildGoModule, ... }: {
> ```

BTW, project has a flake file as well.
So you can do stuff like this:

```
nix run github:bdd/runitor/v1.2.0-beta.1 -- -api-url http://localhost:8880 -uuid <uuid> -- sh -c "echo whee. on a trampoline."
```

**Comment by bdd** [comment]
[v1.2.0](https://github.com/bdd/runitor/releases/tag/v1.2.0) is out.

Thank you @apeschar for your contribution.
Thank you @GermanCoding for testing.
