### ISSUE TITLE
Debian repository

### ISSUE THREAD

**Issue by Derkades** [bdd/runitor#8]
This cool project was missing a debian repository so I took it as an opportunity to learn how that works. I'm not sure if you are interested in adding a stranger's third party repository to your project's readme, though if you are, here it is:
```
echo "deb [arch=amd64] https://deb.derkad.es any main" > /etc/apt/sources.list.d/derkades.list
wget -O - https://deb.derkad.es/gpg.key | sudo apt-key add -
apt update
apt install runitor
```

For now only amd64 but I will add arm and arm64 in the future once I figure out multiarch deb packaging

**Comment by bdd** [comment]
Thanks for contributing this.

Sadly I don't plan to link to binary or source distributions I don't have direct control of.

If you'd be interested in contributing the `debian` directory along with `rules` and entire control archive, I think we can put it under a `contrib` directory along with short dpkg building instructions. This will be useful for those who strictly want dkpgs installed against the base image.

Maybe in the future [GitHub Packages](https://github.com/features/packages) will add APT and Yum repository support, so we can build the binary packages with GitHub Actions using your contribution and publish there.

**Comment by Derkades** [comment]
That's understandable. Regarding deb package building, without apt nicely updating packages from a repo I don't see the point in building a deb package instead of downloading the binary to /usr/local/bin. I wouldn't consider my hacked together control files to be worthy of contributions anyway. It would be great if GitHub provided debian repositories indeed.

**Comment by singpolyma** [comment]
Related to this, just an FYI that runitor is now included in Guix.

**Comment by bdd** [comment]
Nice.
I intend to make a Nix package when I can find some time on a weekend.
